FROM nginx
COPY cert-with-chain.pem /etc/pki/ontoserver/certs/cert-with-chain.pem
COPY private.pem /etc/pki/ontoserver/certs/private.pem
COPY chain.pem /etc/pki/ontoserver/chain/chain.pem
COPY nginx.conf /etc/nginx/nginx.conf
